/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { HierarchyChangeDetail, User, UserEventDetail } from "./components/sp-org-chart/types/org-chart.types";
import { Scene, SceneChangeDetail, TimelineUpdateDetail } from "./components/sp-walkthrough/types/walkthrough.types";
export { HierarchyChangeDetail, User, UserEventDetail } from "./components/sp-org-chart/types/org-chart.types";
export { Scene, SceneChangeDetail, TimelineUpdateDetail } from "./components/sp-walkthrough/types/walkthrough.types";
export namespace Components {
    interface SpExample {
        /**
          * Heading text to display
          * @default 'Example Component'
         */
        "heading": string;
        /**
          * Theme override for standalone usage
          * @type {'light' | 'dark' | 'auto'}
          * @default 'auto'
         */
        "theme": 'light' | 'dark' | 'auto';
    }
    interface SpOrgChart {
        /**
          * Clear all highlights
         */
        "clearHighlight": () => Promise<void>;
        /**
          * Enable/disable edit mode for drag-and-drop and deletion
          * @default false
         */
        "editable": boolean;
        /**
          * Get the currently selected user
         */
        "getSelected": () => Promise<User | null>;
        /**
          * Highlight a specific user by ID
         */
        "highlightUser": (userId: string) => Promise<void>;
        /**
          * Custom message when users array is empty
          * @default 'No data available'
         */
        "noDataMessage": string;
        /**
          * Scroll a user tile into view with smooth animation
         */
        "scrollToUser": (userId: string) => Promise<void>;
        /**
          * Theme override for standalone usage
          * @default 'auto'
         */
        "theme": 'light' | 'dark' | 'auto';
        /**
          * Flat array of users with reporting relationships
          * @default []
         */
        "users": User[];
    }
    /**
     * Interactive walkthrough component with video playback and DOM element highlighting
     */
    interface SpWalkthrough {
        /**
          * Abort walkthrough (cleans up and hides)
         */
        "abort": () => Promise<void>;
        /**
          * Author mode (stub for Plan 02)
          * @default false
         */
        "authorMode": boolean;
        /**
          * Auto-play video on show
          * @default false
         */
        "autoPlay": boolean;
        /**
          * WebVTT captions file URL
         */
        "captionsSrc"?: string;
        /**
          * Hide the walkthrough
         */
        "hide": () => Promise<void>;
        /**
          * Pause video
         */
        "pause": () => Promise<void>;
        /**
          * Play video
         */
        "play": () => Promise<void>;
        /**
          * Restart walkthrough from beginning
         */
        "restart": () => Promise<void>;
        /**
          * Array of walkthrough scenes
          * @default []
         */
        "scenes": Scene[];
        /**
          * Show the walkthrough
         */
        "show": () => Promise<void>;
        /**
          * Theme override
          * @default 'auto'
         */
        "theme": 'light' | 'dark' | 'auto';
        /**
          * Video source URL (MP4/WebM/YouTube) - optional for manual-only mode
         */
        "videoSrc"?: string;
    }
}
export interface SpExampleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpExampleElement;
}
export interface SpOrgChartCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpOrgChartElement;
}
export interface SpWalkthroughCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpWalkthroughElement;
}
declare global {
    interface HTMLSpExampleElementEventMap {
        "spExampleClick": void;
    }
    interface HTMLSpExampleElement extends Components.SpExample, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpExampleElementEventMap>(type: K, listener: (this: HTMLSpExampleElement, ev: SpExampleCustomEvent<HTMLSpExampleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpExampleElementEventMap>(type: K, listener: (this: HTMLSpExampleElement, ev: SpExampleCustomEvent<HTMLSpExampleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpExampleElement: {
        prototype: HTMLSpExampleElement;
        new (): HTMLSpExampleElement;
    };
    interface HTMLSpOrgChartElementEventMap {
        "userClick": UserEventDetail;
        "userDblclick": UserEventDetail;
        "hierarchyChange": HierarchyChangeDetail;
        "userDelete": UserEventDetail;
    }
    interface HTMLSpOrgChartElement extends Components.SpOrgChart, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpOrgChartElementEventMap>(type: K, listener: (this: HTMLSpOrgChartElement, ev: SpOrgChartCustomEvent<HTMLSpOrgChartElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpOrgChartElementEventMap>(type: K, listener: (this: HTMLSpOrgChartElement, ev: SpOrgChartCustomEvent<HTMLSpOrgChartElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpOrgChartElement: {
        prototype: HTMLSpOrgChartElement;
        new (): HTMLSpOrgChartElement;
    };
    interface HTMLSpWalkthroughElementEventMap {
        "walkthroughShown": void;
        "walkthroughHidden": void;
        "walkthroughAborted": void;
        "sceneChanged": SceneChangeDetail;
        "timelineUpdated": TimelineUpdateDetail;
    }
    /**
     * Interactive walkthrough component with video playback and DOM element highlighting
     */
    interface HTMLSpWalkthroughElement extends Components.SpWalkthrough, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpWalkthroughElementEventMap>(type: K, listener: (this: HTMLSpWalkthroughElement, ev: SpWalkthroughCustomEvent<HTMLSpWalkthroughElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpWalkthroughElementEventMap>(type: K, listener: (this: HTMLSpWalkthroughElement, ev: SpWalkthroughCustomEvent<HTMLSpWalkthroughElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpWalkthroughElement: {
        prototype: HTMLSpWalkthroughElement;
        new (): HTMLSpWalkthroughElement;
    };
    interface HTMLElementTagNameMap {
        "sp-example": HTMLSpExampleElement;
        "sp-org-chart": HTMLSpOrgChartElement;
        "sp-walkthrough": HTMLSpWalkthroughElement;
    }
}
declare namespace LocalJSX {
    interface SpExample {
        /**
          * Heading text to display
          * @default 'Example Component'
         */
        "heading"?: string;
        /**
          * Emitted when the button is clicked
         */
        "onSpExampleClick"?: (event: SpExampleCustomEvent<void>) => void;
        /**
          * Theme override for standalone usage
          * @type {'light' | 'dark' | 'auto'}
          * @default 'auto'
         */
        "theme"?: 'light' | 'dark' | 'auto';
    }
    interface SpOrgChart {
        /**
          * Enable/disable edit mode for drag-and-drop and deletion
          * @default false
         */
        "editable"?: boolean;
        /**
          * Custom message when users array is empty
          * @default 'No data available'
         */
        "noDataMessage"?: string;
        /**
          * Emitted when hierarchy changes via drag-and-drop
         */
        "onHierarchyChange"?: (event: SpOrgChartCustomEvent<HierarchyChangeDetail>) => void;
        /**
          * Emitted when a user tile is clicked
         */
        "onUserClick"?: (event: SpOrgChartCustomEvent<UserEventDetail>) => void;
        /**
          * Emitted when a user tile is double-clicked
         */
        "onUserDblclick"?: (event: SpOrgChartCustomEvent<UserEventDetail>) => void;
        /**
          * Emitted when a user is deleted
         */
        "onUserDelete"?: (event: SpOrgChartCustomEvent<UserEventDetail>) => void;
        /**
          * Theme override for standalone usage
          * @default 'auto'
         */
        "theme"?: 'light' | 'dark' | 'auto';
        /**
          * Flat array of users with reporting relationships
          * @default []
         */
        "users"?: User[];
    }
    /**
     * Interactive walkthrough component with video playback and DOM element highlighting
     */
    interface SpWalkthrough {
        /**
          * Author mode (stub for Plan 02)
          * @default false
         */
        "authorMode"?: boolean;
        /**
          * Auto-play video on show
          * @default false
         */
        "autoPlay"?: boolean;
        /**
          * WebVTT captions file URL
         */
        "captionsSrc"?: string;
        /**
          * Emitted when scene changes
         */
        "onSceneChanged"?: (event: SpWalkthroughCustomEvent<SceneChangeDetail>) => void;
        /**
          * Emitted when timeline is updated (author mode)
         */
        "onTimelineUpdated"?: (event: SpWalkthroughCustomEvent<TimelineUpdateDetail>) => void;
        /**
          * Emitted when walkthrough is aborted (ESC key or abort method)
         */
        "onWalkthroughAborted"?: (event: SpWalkthroughCustomEvent<void>) => void;
        /**
          * Emitted when walkthrough is hidden
         */
        "onWalkthroughHidden"?: (event: SpWalkthroughCustomEvent<void>) => void;
        /**
          * Emitted when walkthrough is shown
         */
        "onWalkthroughShown"?: (event: SpWalkthroughCustomEvent<void>) => void;
        /**
          * Array of walkthrough scenes
          * @default []
         */
        "scenes"?: Scene[];
        /**
          * Theme override
          * @default 'auto'
         */
        "theme"?: 'light' | 'dark' | 'auto';
        /**
          * Video source URL (MP4/WebM/YouTube) - optional for manual-only mode
         */
        "videoSrc"?: string;
    }
    interface IntrinsicElements {
        "sp-example": SpExample;
        "sp-org-chart": SpOrgChart;
        "sp-walkthrough": SpWalkthrough;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sp-example": LocalJSX.SpExample & JSXBase.HTMLAttributes<HTMLSpExampleElement>;
            "sp-org-chart": LocalJSX.SpOrgChart & JSXBase.HTMLAttributes<HTMLSpOrgChartElement>;
            /**
             * Interactive walkthrough component with video playback and DOM element highlighting
             */
            "sp-walkthrough": LocalJSX.SpWalkthrough & JSXBase.HTMLAttributes<HTMLSpWalkthroughElement>;
        }
    }
}
