/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ContentChangeEvent, EditorMode, ExportEvent, ImagePasteEvent, ImportEvent, ModeChangeEvent, SaveEvent } from "./components/sp-markdown-editor/types/editor.types";
import { BranchFilterMode, HierarchyChangeDetail, User, UserEventDetail } from "./components/sp-org-chart/types/org-chart.types";
import { Placement } from "./components/sp-popover/types";
import { Scene, SceneChangeDetail, TimelineUpdateDetail } from "./components/sp-walkthrough/types/walkthrough.types";
export { ContentChangeEvent, EditorMode, ExportEvent, ImagePasteEvent, ImportEvent, ModeChangeEvent, SaveEvent } from "./components/sp-markdown-editor/types/editor.types";
export { BranchFilterMode, HierarchyChangeDetail, User, UserEventDetail } from "./components/sp-org-chart/types/org-chart.types";
export { Placement } from "./components/sp-popover/types";
export { Scene, SceneChangeDetail, TimelineUpdateDetail } from "./components/sp-walkthrough/types/walkthrough.types";
export namespace Components {
    interface SpExample {
        /**
          * Heading text to display
          * @default 'Example Component'
         */
        "heading": string;
        /**
          * Theme override for standalone usage
          * @type {'light' | 'dark' | 'auto'}
          * @default 'auto'
         */
        "theme": 'light' | 'dark' | 'auto';
    }
    /**
     * Rich markdown editor component with source, WYSIWYG, and split editing modes.
     * Supports voice dictation, undo/redo history, auto-save, file import/export, and print.
     */
    interface SpMarkdownEditor {
        /**
          * @default true
         */
        "autoSave": boolean;
        /**
          * @default 2000
         */
        "autoSaveDelay": number;
        "clear": () => Promise<void>;
        "focusEditor": () => Promise<void>;
        "getContent": () => Promise<string>;
        "getMode": () => Promise<EditorMode>;
        "isDirty": () => Promise<boolean>;
        /**
          * @default 50
         */
        "maxHistory": number;
        /**
          * @default 'source'
         */
        "mode": EditorMode;
        /**
          * @default 'Start typing markdown...'
         */
        "placeholder": string;
        "setContent": (value: string) => Promise<void>;
        "setMode": (mode: EditorMode) => Promise<void>;
        /**
          * @default ''
         */
        "value": string;
    }
    interface SpOrgChart {
        /**
          * Clear all highlights
         */
        "clearHighlight": () => Promise<void>;
        /**
          * Enable/disable edit mode for drag-and-drop and deletion
          * @default true
         */
        "editable": boolean;
        /**
          * Branch ID to filter by when filterMode is not 'none'
          * @default ''
         */
        "filterBranchId": string;
        /**
          * Branch filter mode — 'none' shows all, 'highlight' dims non-matching, 'isolate' hides unrelated branches
          * @default 'none'
         */
        "filterMode": BranchFilterMode;
        /**
          * Get the currently selected user
         */
        "getSelected": () => Promise<User | null>;
        /**
          * Highlight a specific user by ID
         */
        "highlightUser": (userId: string) => Promise<void>;
        /**
          * Custom message when users array is empty
          * @default 'No data available'
         */
        "noDataMessage": string;
        /**
          * Scroll a user tile into view with smooth animation
         */
        "scrollToUser": (userId: string) => Promise<void>;
        /**
          * Theme override for standalone usage
          * @default 'auto'
         */
        "theme": 'light' | 'dark' | 'auto';
        /**
          * Flat array of users with reporting relationships
          * @default []
         */
        "users": User[];
    }
    interface SpPopover {
        /**
          * Anchor element reference. Can be: - A CSS selector string (resolved via document.querySelector) - A direct HTMLElement reference - null/omitted: uses the previous sibling element
          * @default null
         */
        "anchor": string | HTMLElement;
        /**
          * Close the popover when clicking outside it and its anchor (POPV-03).
          * @default true
         */
        "closeOnClick": boolean;
        /**
          * Close the popover when pressing the Escape key (POPV-03).
          * @default true
         */
        "closeOnEscape": boolean;
        /**
          * Close the popover and emit popover-close (POPV-04)
         */
        "hidePopover": () => Promise<void>;
        /**
          * Controls visibility. Can be bound via prop or toggled via methods. Reflects to attribute.
          * @default false
         */
        "open": boolean;
        /**
          * Preferred placement of the popover relative to its anchor (POPV-01). Will auto-flip if it overflows the viewport (POPV-02).
          * @type {'bottom-start' | 'bottom-end' | 'top-start' | 'top-end' | 'right-start' | 'left-start'}
          * @default 'bottom-start'
         */
        "placement": Placement;
        /**
          * Open the popover, calculate position, and emit popover-open (POPV-04)
         */
        "showPopover": () => Promise<void>;
        /**
          * Theme override for standalone usage.
          * @type {'light' | 'dark' | 'auto'}
          * @default 'auto'
         */
        "theme": 'light' | 'dark' | 'auto';
        /**
          * Toggle between open and closed states (POPV-04)
         */
        "togglePopover": () => Promise<void>;
        /**
          * Recalculate position without changing open state. Useful after scroll/resize events (POPV-04).
         */
        "updatePosition": () => Promise<void>;
    }
    /**
     * Interactive walkthrough component with video playback and DOM element highlighting.
     * Renders a draggable floating panel with scene navigation, video controls, and author mode for scene creation.
     * Note: sp-walkthrough does not expose CSS parts. The panel is a self-contained overlay UI and
     * is not designed for external structural customization via ::part() selectors. Use CSS custom
     * properties (--dwc-*) to theme colors, spacing, and typography.
     */
    interface SpWalkthrough {
        /**
          * Abort walkthrough (cleans up and hides)
         */
        "abort": () => Promise<void>;
        /**
          * Author mode - enables scene editing and pointer tool
          * @default false
         */
        "authorMode": boolean;
        /**
          * Auto-play video on show
          * @default false
         */
        "autoPlay": boolean;
        /**
          * WebVTT captions file URL
         */
        "captionsSrc"?: string;
        /**
          * Hide the walkthrough
         */
        "hide": () => Promise<void>;
        /**
          * Pause video
         */
        "pause": () => Promise<void>;
        /**
          * Play video
         */
        "play": () => Promise<void>;
        /**
          * Restart walkthrough from beginning
         */
        "restart": () => Promise<void>;
        /**
          * Array of walkthrough scenes
          * @default []
         */
        "scenes": Scene[];
        /**
          * Show the walkthrough
         */
        "show": () => Promise<void>;
        /**
          * Theme override
          * @default 'auto'
         */
        "theme": 'light' | 'dark' | 'auto';
        /**
          * Video source URL (MP4/WebM/YouTube) - optional for manual-only mode
         */
        "videoSrc"?: string;
    }
}
export interface SpExampleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpExampleElement;
}
export interface SpMarkdownEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpMarkdownEditorElement;
}
export interface SpOrgChartCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpOrgChartElement;
}
export interface SpPopoverCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpPopoverElement;
}
export interface SpWalkthroughCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpWalkthroughElement;
}
declare global {
    interface HTMLSpExampleElementEventMap {
        "spExampleClick": void;
    }
    interface HTMLSpExampleElement extends Components.SpExample, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpExampleElementEventMap>(type: K, listener: (this: HTMLSpExampleElement, ev: SpExampleCustomEvent<HTMLSpExampleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpExampleElementEventMap>(type: K, listener: (this: HTMLSpExampleElement, ev: SpExampleCustomEvent<HTMLSpExampleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpExampleElement: {
        prototype: HTMLSpExampleElement;
        new (): HTMLSpExampleElement;
    };
    interface HTMLSpMarkdownEditorElementEventMap {
        "contentChange": ContentChangeEvent;
        "save": SaveEvent;
        "modeChange": ModeChangeEvent;
        "importFile": ImportEvent;
        "exportFile": ExportEvent;
        "imagePaste": ImagePasteEvent;
    }
    /**
     * Rich markdown editor component with source, WYSIWYG, and split editing modes.
     * Supports voice dictation, undo/redo history, auto-save, file import/export, and print.
     */
    interface HTMLSpMarkdownEditorElement extends Components.SpMarkdownEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpMarkdownEditorElementEventMap>(type: K, listener: (this: HTMLSpMarkdownEditorElement, ev: SpMarkdownEditorCustomEvent<HTMLSpMarkdownEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpMarkdownEditorElementEventMap>(type: K, listener: (this: HTMLSpMarkdownEditorElement, ev: SpMarkdownEditorCustomEvent<HTMLSpMarkdownEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpMarkdownEditorElement: {
        prototype: HTMLSpMarkdownEditorElement;
        new (): HTMLSpMarkdownEditorElement;
    };
    interface HTMLSpOrgChartElementEventMap {
        "userClick": UserEventDetail;
        "userDblclick": UserEventDetail;
        "hierarchyChange": HierarchyChangeDetail;
        "userDelete": UserEventDetail;
    }
    interface HTMLSpOrgChartElement extends Components.SpOrgChart, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpOrgChartElementEventMap>(type: K, listener: (this: HTMLSpOrgChartElement, ev: SpOrgChartCustomEvent<HTMLSpOrgChartElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpOrgChartElementEventMap>(type: K, listener: (this: HTMLSpOrgChartElement, ev: SpOrgChartCustomEvent<HTMLSpOrgChartElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpOrgChartElement: {
        prototype: HTMLSpOrgChartElement;
        new (): HTMLSpOrgChartElement;
    };
    interface HTMLSpPopoverElementEventMap {
        "popoverOpen": void;
        "popoverClose": void;
    }
    interface HTMLSpPopoverElement extends Omit<Components.SpPopover, "showPopover" | "hidePopover" | "togglePopover">, HTMLStencilElement {
        /**
          * Open the popover, calculate position, and emit popover-open (POPV-04)
         */
        "showPopover": () => Promise<void>;
        /**
          * Close the popover and emit popover-close (POPV-04)
         */
        "hidePopover": () => Promise<void>;
        /**
          * Toggle between open and closed states (POPV-04)
         */
        "togglePopover": () => Promise<void>;
        addEventListener<K extends keyof HTMLSpPopoverElementEventMap>(type: K, listener: (this: HTMLSpPopoverElement, ev: SpPopoverCustomEvent<HTMLSpPopoverElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpPopoverElementEventMap>(type: K, listener: (this: HTMLSpPopoverElement, ev: SpPopoverCustomEvent<HTMLSpPopoverElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpPopoverElement: {
        prototype: HTMLSpPopoverElement;
        new (): HTMLSpPopoverElement;
    };
    interface HTMLSpWalkthroughElementEventMap {
        "walkthroughShown": void;
        "walkthroughHidden": void;
        "walkthroughAborted": void;
        "sceneChanged": SceneChangeDetail;
        "timelineUpdated": TimelineUpdateDetail;
    }
    /**
     * Interactive walkthrough component with video playback and DOM element highlighting.
     * Renders a draggable floating panel with scene navigation, video controls, and author mode for scene creation.
     * Note: sp-walkthrough does not expose CSS parts. The panel is a self-contained overlay UI and
     * is not designed for external structural customization via ::part() selectors. Use CSS custom
     * properties (--dwc-*) to theme colors, spacing, and typography.
     */
    interface HTMLSpWalkthroughElement extends Components.SpWalkthrough, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpWalkthroughElementEventMap>(type: K, listener: (this: HTMLSpWalkthroughElement, ev: SpWalkthroughCustomEvent<HTMLSpWalkthroughElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpWalkthroughElementEventMap>(type: K, listener: (this: HTMLSpWalkthroughElement, ev: SpWalkthroughCustomEvent<HTMLSpWalkthroughElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpWalkthroughElement: {
        prototype: HTMLSpWalkthroughElement;
        new (): HTMLSpWalkthroughElement;
    };
    interface HTMLElementTagNameMap {
        "sp-example": HTMLSpExampleElement;
        "sp-markdown-editor": HTMLSpMarkdownEditorElement;
        "sp-org-chart": HTMLSpOrgChartElement;
        "sp-popover": HTMLSpPopoverElement;
        "sp-walkthrough": HTMLSpWalkthroughElement;
    }
}
declare namespace LocalJSX {
    interface SpExample {
        /**
          * Heading text to display
          * @default 'Example Component'
         */
        "heading"?: string;
        /**
          * Emitted when the button is clicked
         */
        "onSpExampleClick"?: (event: SpExampleCustomEvent<void>) => void;
        /**
          * Theme override for standalone usage
          * @type {'light' | 'dark' | 'auto'}
          * @default 'auto'
         */
        "theme"?: 'light' | 'dark' | 'auto';
    }
    /**
     * Rich markdown editor component with source, WYSIWYG, and split editing modes.
     * Supports voice dictation, undo/redo history, auto-save, file import/export, and print.
     */
    interface SpMarkdownEditor {
        /**
          * @default true
         */
        "autoSave"?: boolean;
        /**
          * @default 2000
         */
        "autoSaveDelay"?: number;
        /**
          * @default 50
         */
        "maxHistory"?: number;
        /**
          * @default 'source'
         */
        "mode"?: EditorMode;
        "onContentChange"?: (event: SpMarkdownEditorCustomEvent<ContentChangeEvent>) => void;
        "onExportFile"?: (event: SpMarkdownEditorCustomEvent<ExportEvent>) => void;
        "onImagePaste"?: (event: SpMarkdownEditorCustomEvent<ImagePasteEvent>) => void;
        "onImportFile"?: (event: SpMarkdownEditorCustomEvent<ImportEvent>) => void;
        "onModeChange"?: (event: SpMarkdownEditorCustomEvent<ModeChangeEvent>) => void;
        "onSave"?: (event: SpMarkdownEditorCustomEvent<SaveEvent>) => void;
        /**
          * @default 'Start typing markdown...'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface SpOrgChart {
        /**
          * Enable/disable edit mode for drag-and-drop and deletion
          * @default true
         */
        "editable"?: boolean;
        /**
          * Branch ID to filter by when filterMode is not 'none'
          * @default ''
         */
        "filterBranchId"?: string;
        /**
          * Branch filter mode — 'none' shows all, 'highlight' dims non-matching, 'isolate' hides unrelated branches
          * @default 'none'
         */
        "filterMode"?: BranchFilterMode;
        /**
          * Custom message when users array is empty
          * @default 'No data available'
         */
        "noDataMessage"?: string;
        /**
          * Emitted when hierarchy changes via drag-and-drop
         */
        "onHierarchyChange"?: (event: SpOrgChartCustomEvent<HierarchyChangeDetail>) => void;
        /**
          * Emitted when a user tile is clicked
         */
        "onUserClick"?: (event: SpOrgChartCustomEvent<UserEventDetail>) => void;
        /**
          * Emitted when a user tile is double-clicked
         */
        "onUserDblclick"?: (event: SpOrgChartCustomEvent<UserEventDetail>) => void;
        /**
          * Emitted when a user is deleted
         */
        "onUserDelete"?: (event: SpOrgChartCustomEvent<UserEventDetail>) => void;
        /**
          * Theme override for standalone usage
          * @default 'auto'
         */
        "theme"?: 'light' | 'dark' | 'auto';
        /**
          * Flat array of users with reporting relationships
          * @default []
         */
        "users"?: User[];
    }
    interface SpPopover {
        /**
          * Anchor element reference. Can be: - A CSS selector string (resolved via document.querySelector) - A direct HTMLElement reference - null/omitted: uses the previous sibling element
          * @default null
         */
        "anchor"?: string | HTMLElement;
        /**
          * Close the popover when clicking outside it and its anchor (POPV-03).
          * @default true
         */
        "closeOnClick"?: boolean;
        /**
          * Close the popover when pressing the Escape key (POPV-03).
          * @default true
         */
        "closeOnEscape"?: boolean;
        /**
          * Emitted when the popover closes (POPV-06)
         */
        "onPopoverClose"?: (event: SpPopoverCustomEvent<void>) => void;
        /**
          * Emitted when the popover opens (POPV-06)
         */
        "onPopoverOpen"?: (event: SpPopoverCustomEvent<void>) => void;
        /**
          * Controls visibility. Can be bound via prop or toggled via methods. Reflects to attribute.
          * @default false
         */
        "open"?: boolean;
        /**
          * Preferred placement of the popover relative to its anchor (POPV-01). Will auto-flip if it overflows the viewport (POPV-02).
          * @type {'bottom-start' | 'bottom-end' | 'top-start' | 'top-end' | 'right-start' | 'left-start'}
          * @default 'bottom-start'
         */
        "placement"?: Placement;
        /**
          * Theme override for standalone usage.
          * @type {'light' | 'dark' | 'auto'}
          * @default 'auto'
         */
        "theme"?: 'light' | 'dark' | 'auto';
    }
    /**
     * Interactive walkthrough component with video playback and DOM element highlighting.
     * Renders a draggable floating panel with scene navigation, video controls, and author mode for scene creation.
     * Note: sp-walkthrough does not expose CSS parts. The panel is a self-contained overlay UI and
     * is not designed for external structural customization via ::part() selectors. Use CSS custom
     * properties (--dwc-*) to theme colors, spacing, and typography.
     */
    interface SpWalkthrough {
        /**
          * Author mode - enables scene editing and pointer tool
          * @default false
         */
        "authorMode"?: boolean;
        /**
          * Auto-play video on show
          * @default false
         */
        "autoPlay"?: boolean;
        /**
          * WebVTT captions file URL
         */
        "captionsSrc"?: string;
        /**
          * Emitted when scene changes
         */
        "onSceneChanged"?: (event: SpWalkthroughCustomEvent<SceneChangeDetail>) => void;
        /**
          * Emitted when timeline is updated (author mode)
         */
        "onTimelineUpdated"?: (event: SpWalkthroughCustomEvent<TimelineUpdateDetail>) => void;
        /**
          * Emitted when walkthrough is aborted (ESC key or abort method)
         */
        "onWalkthroughAborted"?: (event: SpWalkthroughCustomEvent<void>) => void;
        /**
          * Emitted when walkthrough is hidden
         */
        "onWalkthroughHidden"?: (event: SpWalkthroughCustomEvent<void>) => void;
        /**
          * Emitted when walkthrough is shown
         */
        "onWalkthroughShown"?: (event: SpWalkthroughCustomEvent<void>) => void;
        /**
          * Array of walkthrough scenes
          * @default []
         */
        "scenes"?: Scene[];
        /**
          * Theme override
          * @default 'auto'
         */
        "theme"?: 'light' | 'dark' | 'auto';
        /**
          * Video source URL (MP4/WebM/YouTube) - optional for manual-only mode
         */
        "videoSrc"?: string;
    }
    interface IntrinsicElements {
        "sp-example": SpExample;
        "sp-markdown-editor": SpMarkdownEditor;
        "sp-org-chart": SpOrgChart;
        "sp-popover": SpPopover;
        "sp-walkthrough": SpWalkthrough;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sp-example": LocalJSX.SpExample & JSXBase.HTMLAttributes<HTMLSpExampleElement>;
            /**
             * Rich markdown editor component with source, WYSIWYG, and split editing modes.
             * Supports voice dictation, undo/redo history, auto-save, file import/export, and print.
             */
            "sp-markdown-editor": LocalJSX.SpMarkdownEditor & JSXBase.HTMLAttributes<HTMLSpMarkdownEditorElement>;
            "sp-org-chart": LocalJSX.SpOrgChart & JSXBase.HTMLAttributes<HTMLSpOrgChartElement>;
            "sp-popover": LocalJSX.SpPopover & JSXBase.HTMLAttributes<HTMLSpPopoverElement>;
            /**
             * Interactive walkthrough component with video playback and DOM element highlighting.
             * Renders a draggable floating panel with scene navigation, video controls, and author mode for scene creation.
             * Note: sp-walkthrough does not expose CSS parts. The panel is a self-contained overlay UI and
             * is not designed for external structural customization via ::part() selectors. Use CSS custom
             * properties (--dwc-*) to theme colors, spacing, and typography.
             */
            "sp-walkthrough": LocalJSX.SpWalkthrough & JSXBase.HTMLAttributes<HTMLSpWalkthroughElement>;
        }
    }
}
